Repository CareerConnect-Rakamin/back-end-careerConnect, pull requests merged in 2023-11, with the labels that each got.

#22 fix: adjust the register
  src/config/index.js
  src/controllers/auth.controllers.js
  src/controllers/companies.controllers.js
  src/controllers/user-profile.controllers.js
  src/middlewares/validator/auth.requirements.js
  src/middlewares/validator/jobseeker.requirements.js
  src/models/jobSeekers.models.js
  src/services/auth.services.js
  src/services/companies.services.js
  src/services/user-profile.services.js
Labels: bug

#24 Adjust the display of Get Applications by Job Id
  docs/v1/application.js
  docs/v1/auth.js
  src/repositories/applications.repositories.js
  src/services/applications.services.js
  src/utils/calculateAge.js
Labels: documentation, enhancement

#25 add search function for get all companies and get all jobs
  docs/v1/company.js
  docs/v1/job.js
  src/controllers/companies.controllers.js
  src/controllers/jobs.controllers.js
  src/repositories/companies.repositories.js
  src/repositories/jobs.repositories.js
  src/services/companies.services.js
  src/services/jobs.services.js
Labels: documentation, enhancement

#26 fix: add search feature for /jobs endpoint
  src/middlewares/validator/jobs.requirements.js
  src/repositories/jobs.repositories.js
  src/services/jobs.services.js
Labels: enhancement

#27 add more data dummy for user, jobseeker, company and jobs
  src/middlewares/validator/company.requirements.js
  src/middlewares/validator/jobs.requirements.js
  src/models/companies.models.js
  src/models/jobs.models.js
  src/seeders/applications.seeders.js
  src/seeders/companies.seeders.js
  src/seeders/jobSeekers.seeders.js
  src/seeders/jobs.seeders.js
  src/seeders/users.seeders.js
Labels: enhancement

#28 fixing update
  docs/v1/application.js
  src/services/jobs.services.js
Labels: bug

#29 Fix/juna/adjust few responses
  src/controllers/applications.controllers.js
  src/repositories/applications.repositories.js
  src/repositories/companies.repositories.js
  src/repositories/jobs.repositories.js
  src/services/applications.services.js
Labels: bug, enhancement

#32 add closing date to models and the Docs
  docs/v1/component.js
  docs/v1/job.js
  package.json
  src/controllers/jobs.controllers.js
  src/middlewares/validator/jobs.requirements.js
  src/models/jobs.models.js
  src/repositories/jobs.repositories.js
  src/seeders/jobs.seeders.js
  src/server.js
  src/services/jobs.services.js
Labels: bug, enhancement
